version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:10000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/instance/codedswitch.db
      - SECRET_KEY=your-secret-key-here
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=your-email@gmail.com
      - MAIL_PASSWORD=your-email-password
      - STRIPE_SECRET_KEY=your-stripe-secret-key
      - STRIPE_WEBHOOK_SECRET=your-stripe-webhook-secret
      - REDIS_URL=redis://redis:6379/0
      - RQ_REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend/instance:/app/instance
      - ./backend/uploads:/app/uploads
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile.worker
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/instance/codedswitch.db
      - REDIS_URL=redis://redis:6379/0
      - RQ_REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
      - OMP_NUM_THREADS=1
    volumes:
      - ./backend/instance:/app/instance
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

volumes:
  redis_data:
