version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:10000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/instance/codedswitch.db
      - SECRET_KEY=your-secret-key-here
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=your-email@gmail.com
      - MAIL_PASSWORD=your-email-password
      - STRIPE_SECRET_KEY=your-stripe-secret-key
      - STRIPE_WEBHOOK_SECRET=your-stripe-webhook-secret
      - REDIS_URL=redis://redis:6379/0
      - RQ_REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend/instance:/app/instance
      - ./backend/uploads:/app/uploads
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: rq worker --url redis://redis:6379/0
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/instance/codedswitch.db
      - REDIS_URL=redis://redis:6379/0
      - RQ_REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend/instance:/app/instance
      - ./backend/uploads:/app/uploads
    depends_on:
      - redis
      - backend
    restart: unless-stopped

volumes:
  redis_data:
