services:
  - type: web
    name: codedswitch
    env: static
    buildCommand: |
      cd frontend && \
      npm ci --no-audit --prefer-offline && \
      npm run build
    staticPublishPath: "./frontend/dist"
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: VITE_API_URL
        value: https://codedswitch-api.onrender.com
      - key: VITE_ENABLE_ANALYTICS
        value: "false"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

  - type: web
    name: codedswitch-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: gunicorn --worker-class=uvicorn.workers.UvicornWorker backend.web_backend:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    healthCheckPath: /health
    autoDeploy: true
    healthCheckPath: /api/health
