name: CodedSwitch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Install Dependencies
      run: npm ci

    - name: Check Linting
      run: npm run lint || true

    - name: Build Frontend
      run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: frontend/dist

  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: './backend/requirements.txt'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest flake8

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --statistics

    - name: Run Tests
      run: |
        pytest || true

  docker-build:
    runs-on: ubuntu-latest
    needs: [frontend-build, backend-test]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Backend Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./backend/Dockerfile.backend
        push: false
        tags: codedswitch/backend:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Worker Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./backend/Dockerfile.worker
        push: false
        tags: codedswitch/worker:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
